#!/usr/bin/env bash
# install and configure nging on a server

sudo apt-get -y update
sudo apt-get install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
