#!/usr/bin/env bash
# install and configure nging on a server
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
