#!/usr/bin/env bash
# install and configure nging on a server
apt-get update
apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo dd status=none of=/var/www/html/index.html; sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/boulderbugle.com\/bHVw8SFV\/;\\n\\t}/" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
