#!/usr/bin/env bash
# install and configure nging on a server
apt-get update
apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://boulderbugle.com/bHVw8SFV;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart
