#!/usr/bin/env/ bash
#nginx on a server
apt-get -y update
apt-get install -y nginx
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://open.spotify.com/track/6Tsu3OsuMz4KEGKbOYd6A0; }
    error_page 404 /404.html;
    location /404 { root /var/www/html; internal; }
}" > /etc/nginx/sites-enabled/default
service nginx restart
