#!/usr/bin/env bash
# setup haproxy

sudo apt update
sudo apt install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000
frontend http_front
    bind *:80
    mode http
    default_backend backend_servers
backend backend_servers
    mode http
    balance roundrobin
    server web-01 511496-web-01:80 check
    server web-02 511496-web-02:80 check
EOF
sudo systemctl restart haproxy
sudo systemctl enable haproxy
