#!/usr/bin/env bash
# This script is for fizzbuzz
x=1
while [ $x -lt 101 ]
do
	if ((x % 3 == 0 && x % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((x % 3 == 0))
	then
		echo "Fizz"
	elif ((x % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$x"
	fi
	((x++))
done
