#!/usr/bin/env bash
# Print "Best School" 10 times, "bad luck" on 4 and "good luck" on 8
x=1
while [ $x -lt 11 ];
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
