#!/usr/bin/env bash
# run nginx as nginx user
chmod 766 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
pkill -9 apache
sudo -u nginx service nginx restart
